# Generated by Django 5.0.1 on 2024-04-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='utilisateur',
        ),
    ]
