# Generated by Django 5.0.1 on 2024-04-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0002_alter_project_table_alter_task_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_planner.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_planner.utilisateur')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
