# Generated by Django 5.0.1 on 2024-04-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_planner', '0004_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.OneToOneField(default=0.00127635046113307, on_delete=django.db.models.deletion.CASCADE, to='task_planner.deadline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deadline',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
